on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "wd-dm-app-org"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "wd-dm-app-actions"
  TF_LOG: INFO
  CONFIG_DIRECTORY: "./"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./environments/dev

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
     - name: Terraform init
       id: init
       run: terraform init
     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false

